### ISSUE TITLE
Программа не запускалась

### ISSUE THREAD

**Issue by ubaidsworld** [RandomKori/ForexTF#2]
Я пытаюсь запустить вашу программу, но не могу. DLL не загружается. См. Сообщение об ошибке: 
```
2018.04.13 08:39:55.445	2018.03.01 00:00:00   Cannot load 'NewNeuroDense.dll' [126]
2018.04.13 08:39:55.448	2018.03.01 00:00:00   Cannot call 'LoadModel', 'NewNeuroDense.dll' is not loaded
2018.04.13 08:39:55.448	2018.03.01 00:00:00   unresolved import function call
2018.04.13 08:39:55.449	NewNeuroDense (EURUSD,M1) OnInit return code is -1
2018.04.13 08:39:55.449	cannot initialize indicator
```
Даже я не мог видеть файлы, упомянутые в пути:
```
input string   path="D:\\ModelFORTS\\DenseClass";
input int      NBars=1000;
input double   norm=1.0;
input double   Signal=0.5;
input double   NoSignal=0.5;
```
Где это: ` ModelFORTS\\DenseClass`  ?  

Пожалуйста, дайте мне знать.

**Comment by JafferWilson** [comment]
I am having the same issues. Please let me know if you get any solution.
У меня такие же проблемы. Пожалуйста, дайте мне знать, если вы получите какое-либо решение.

**Comment by RandomKori** [comment]
Я не знаю английский язык.

**Comment by ubaidsworld** [comment]
Я написал свою проблему на русском языке, пожалуйста, скажите мне, какое решение?

**Comment by RandomKori** [comment]
Нейронную сеть сначала необходимо обучить. Затем скомпилировать соответствующую DLL и поместить ее в соответствующую папку терминала. Туда же необходимо поместить библиотеку TensorFlow. В индикаторе прописать путь к сохраненной модели. Но все это с точки зрения получения профита бесполезно. Используя выложенный мной здесь код вы ничего путного не получите. Поэтому его лучше использовать как примеры для своих разработок. Все таки желательно хотя бы  минимально разбираться в работе Метатрэйдер 5 и знать Питон.

**Comment by RandomKori** [comment]
Маленькое дополнение скомпилированные DLL есть в папке MQL5. Необходимо просто их скопировать в терминал. Но модель обучить все таки необходимо.
